[project]
name = "tello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "djitellopy>=2.5.0",
    "opencv-python>=4.11.0.86",
]

[tool.uv.workspace]
members = [
    "TelloTV",
]
